theme: just-the-docs

title: OpenRMS
description: tesing a lipsum lorem stuff

project:
  version: 1.0.0
  download_url: https://github.com/USER/PROJECT/releases

license:
  software: MIT License
  software_url: http://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: http://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      url: https://github.com/allejo/jekyll-docs-theme
  footer:
    - title: GitHub
      url: https://github.com/allejo/jekyll-docs-theme
    - title: Issues
      url: https://github.com/allejo/jekyll-docs-theme/issues?state=open

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

social:
  github:
    user: allejo
    repo: jekyll-docs-theme