logging:
  level: trace
  file: openrmsd.log

websocket:
  enabled: true
  port: 8080


implement:
  plugin: generator
  oxigen:
    port: COM5

  generator:
    cars: 1
    interval: 600

race:
  plugin: simple
  max-speed: 255
  pitlane:
    lapcounting:
      enabled: true
      entry: true

car:
  plugin: config
  cars:
    - id: 1
      max-speed: 255
      limb-mode:
        max-speed: 100
    - id: 2
      max-speed: 255


rules:
  - plugin: fuel
    enabled: true

  - plugin: limb-mode
    enabled: true
    max-speed: 50

postprocessors:
  influxdb:
    url: "http://localhost:8086"
    # batch-size: 100
    auth-token: "_esnfjdFsjvkBkgc4S3ovqftb8RmmwAeGDBbt4fsY20EA9pFqeLaNYUkoH3sOyZ9jfTGcML-dB8AKgyj577Qhw=="
    organization: openrms
    bucket: openrms
  websocket:
    listen: ":8080"