# Configure logging level and files
logging:
  # Details of logging output. Possible values are error, warn, info, debug or trace
  level: trace
  # Where should openrms write the log file
  file: openrmsd.log

implement:
  plugin: generator

  oxigen:
    # port: COM7 # Leave blank for auto detection

  generator:
    cars: 5
    interval: 1000

# configure the track, this will define of openrms & oxigen
# handles lap counting, pitting etc.
track:
  # General max speed in percentage
  # format: percentage
  # type: integer
  # allowed range: 0-100
  max-speed: 40

  # Track length is used to calculate average speed of the cars
  # format: meter
  # type: float
  length: 19

  # Pit lane behaviour
  pit-lane:
    lap-counting:
      # Enable lap counting when entering or exiting the pit lane
      enabled: true
      # Count lap on entry or exit
      # type: boolean
      # format: if true count on entry, if false count on exit
      on-entry: false

# Car behaviour
car:
  plugin: config

  # Default car behavior
  # All default values can be mapped to individual
  # cars in the car specific configuration section
  defaults:

    # Default maximum speed of cars
    # format: percentage
    # type: integer
    # allowed range: 0-100
    max-speed: 60

    # Default minimum speed of cars
    # this defines the minimum speed of cars, this can be used to create
    # ghost cars, for example setting this value to 20 will cause all cars
    # to constantly drive at 20% power. the car can still be operated with
    # the controller but the power will never go below 20%
    #
    # format: percentage
    # type: integer
    # allowed range: 0-100
    min-speed: 0


    fuel:
      # Default fuel tank size
      # format: liter
      # type: integer
      # allowed range: 0 - max int
      tank-size: 75

      # Default starting fuel.
      # format: liter
      # type: integer
      # allowed range: 0 - max int
      starting-fuel: 60

      # Default fuel burn rate
      # format: Liter per second at max power
      # type: float
      burn-rate: 0.223

      # Default fuel refuelling flow rate
      # format: Liter per second
      # type: float
      flow-rate: 11.3

    pit-lane:
      # Default maximum pit lane speed of cars
      # format: percentage
      # type: integer
      # allowed range: 0-100
      max-speed: 20

    limb-mode:
      # Default maximum speed of cars when in limb mode
      # Cars can enter limb mode, when it runs out of fuel get damage etc.
      # when a car enter limb mode it must enter the pit and complete a pit
      # stop to disable this state. limb mode can also force the car in to
      # be marked as "did not finish"
      # format: percentage
      # type: integer
      # allowed range: 0-100
      max-speed: 17


  cars:
    - id: 3
      # max-speedrs: 100
      drivers:
        - name: John Doe
    - id: 7
      max-speed: 30
    - id: 8
      max-speed: 100
      pit-lane:
        max-speed: 28
  #  - id: 1
  #    max-speed: 100
  #    fuel: 100
  #    limb-mode:
  #      max-speed: 100
  #  - id: 2
  #    max-speed: 100


plugins:
  fuel:
    enabled: false
  race:
    enabled: true
  telemetry:
    enabled: true
  limb-mode:
    enabled: false
  pit:
    enabled: false
  ontrack:
    enabled: true
    flag: yellow # yellow, green or red
  flag:
    enabled: false
    yellow:
      max-speed: 50
    red:
      pause: true

  confirmation:
    enabled: true



# Configure how the webserver works
webserver:
  # Port for the webserver to listen on
  listen: ":8080"