logging:
  level: trace
  file: openrmsd.log

websocket:
  enabled: true
  port: 8080

implement:
  plugin: oxigen
  oxigen:
    port: COM6

  generator:
    cars: 1
    interval: 1000

track:
  max-speed: 100
  length: 19
  pit-lane:
    lap-counting:
      enabled: true
      on-entry: true

car:
  plugin: config
  defaults:
    max-speed: 100
    min-speed: 0
    fuel: 75
    pit:
      max-speed: 20
    limb-mode:
      max-speed: 75
  cars:
    - id: 3
      max-speed: 75
      driver:
        name: Hans Hansen
  #  - id: 1
  #    max-speed: 100
  #    fuel: 100
  #    limb-mode:
  #      max-speed: 100
  #  - id: 2
  #    max-speed: 100


rules:
  - plugin: race
    enabled: false
    stages:
      - type: training
        duration: 10m
      - type: qualification
        laps: 10
      - type: competition
        duration: 10m


  - plugin: fuel
    enabled: true
    # Default car fuel in liter
    fuel: 75
    burn-rate: 0.033
    # flow-rate: 11.3

  - plugin: limb-mode
    enabled: false
    # Default car limb mode speed (0-255)
    max-speed: 60

  - plugin: pit
    enabled: true

#  - plugin: damage
#    enabled: true

#  - plugin: tirewear
#    enabled: true

  - plugin: leaderboard
    enabled: false

webserver:
  listen: ":8080"

postprocessors:
  influxdb:
    url: "http://192.168.37.171:8086"
    batch-size: 100
    auth-token: "445DAYLEv4M17iT6nzeSbJ3TRVJQ7fJnNF7v1u8ItuaiE3Ou5nBcG9u0XRedw77tizKnT2rbGxm7KtFHDqYeqQ=="
    organization: openrms
    bucket: openrms
  leaderboard: {}
