logging:
  level: trace
  file: openrmsd.log

websocket:
  enabled: true
  port: 8080


implement:
  plugin: oxigen
  oxigen:
    port: /dev/ttyACM0

  generator:
    cars: 2
    interval: 1000

course:
  max-speed: 100
  length: 19
  pitlane:
    lap-counting:
      enabled: true
      on-entry: false

car:
  plugin: config
  defaults:
    max-speed: 255
    fuel: 75
    pit:
      max-speed: 75
    limb-mode:
      max-speed: 75
  cars:
    - id: 1
      max-speed: 255
      fuel: 100
      limb-mode:
        max-speed: 100
    - id: 2
      max-speed: 255


rules:
  - plugin: race
    enabled: false
    stages:
      - type: training
        duration: 1m
      - type: qualification
        laps: 10
      - type: competition
        duration: 10m


  - plugin: fuel
    enabled: true
    # Default car fuel in liter
    fuel: 75
    burn-rate: 0.033
    # flow-rate: 11.3

  - plugin: limb-mode
    enabled: true
    # Default car limb mode speed (0-255)
    max-speed: 60

  - plugin: pit
    enabled: true

#  - plugin: damage
#    enabled: true

#  - plugin: tirewear
#    enabled: true

  - plugin: leaderboard
    enabled: true


postprocessors:
  influxdb:
    url: "http://localhost:8086"
    batch-size: 100
    auth-token: "445DAYLEv4M17iT6nzeSbJ3TRVJQ7fJnNF7v1u8ItuaiE3Ou5nBcG9u0XRedw77tizKnT2rbGxm7KtFHDqYeqQ=="
    organization: openrms
    bucket: openrms
  websocket:
    listen: ":8080"