implement:
  plugin: oxigen
  oxigen:
    port: COM5


race:
  plugin: simple
  max-speed: 255
  pitlane:
    lapcounting:
      enabled: true
      entry: true


car:
  plugin: list
  cars:
    - id: 1
      max-speed: 255
    - id: 2
      max-speed: 255

rules:
  - plugin: fuel
    enabled: true

  - plugin: limb-mode
    enabled: true
    max-speed: 50

telemetry:
  plugin: influxdb
  influxdb:
    url: "http://localhost:8086"
    # batch-size: 100
    auth-token: "_esnfjdFsjvkBkgc4S3ovqftb8RmmwAeGDBbt4fsY20EA9pFqeLaNYUkoH3sOyZ9jfTGcML-dB8AKgyj577Qhw=="
    organization: openrms
    bucket: openrms
